import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import { NavigationBar } from "@/components/navigation/Navigationbar";

const fontFamily = Barlow({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontFamily.className}`}>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
